### ISSUE TITLE
I can't download the files from https://weizmann.box.com/v/SGVF-DataFiles to the folder containing the code files.

### ISSUE THREAD

**Issue by 1399332989** [segalab/SGVFinder#1]
I am a user from China.I can't download the files from https://weizmann.box.com/v/SGVF-DataFiles to the folder containing the code files.Is there another way to download these files?

**Comment by talkr** [comment]
Is this a problem specific to box? Would uploading to a different service fix it for you?

**Comment by 1399332989** [comment]
Since some websites are restricted in China, changing to another server accessible in China should solve this problem.For example, Zenodo is available in China.


 
---Original---

**Comment by talkr** [comment]
Now available also through Zenodo https://zenodo.org/record/3237975#.XPc0uJxRWhc

Thank you or your patience.

**Comment by treasure316** [comment]
你好，我也是中国的用户，请问可以跟您探讨一下安装问题嘛？
