### ISSUE TITLE
Error in work_on_collection functino 

### ISSUE THREAD

**Issue by xif033** [segalab/SGVFinder#15]
Hello, 

I have been able to generate the jsdel and pmp files successfully on a HPC cluster for around 120 samples, but I have encountered an error when I tried to generate the SV dataframes. The error message is: /home/xif033/miniconda3/envs/SGVtest/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:589: RuntimeWarning: divide by zero encountered in true_divide
  a/(b-1.0),
/home/xif033/miniconda3/envs/SGVtest/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:593: RuntimeWarning: divide by zero encountered in true_divide
  a*(a+1.0)/((b-2.0)*(b-1.0)),
/home/xif033/miniconda3/envs/SGVtest/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1037: RuntimeWarning: invalid value encountered in subtract
  mu2 = mu2p - mu * mu
/home/xif033/miniconda3/envs/SGVtest/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:2305: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu
/home/xif033/miniconda3/envs/SGVtest/lib/python2.7/site-packages/numpy/lib/function_base.py:4033: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
Traceback (most recent call last):
  File "/home/xif033/tools/SGVFinder-master/src/SGV_test.py", line 30, in <module>
    vsgv, dsgv = work_on_collection(samp_to_map, 10, 0.25, 0.95, 0.25, 0.125, 0.02, 0.95, 'betaprime', 0.01, 10, 85, join(OUTPUT_FOLDER, 'browser'))
  File "/home/xif033/tools/SGVFinder-master/src/SGVFinder.py", line 172, in work_on_collection
    deldf, delsregions, bacdf, sgvregions, browser_path, genepos)
  File "/home/xif033/tools/SGVFinder-master/src/SGVFinder.py", line 427, in draw_one_region
    bpl.save(column(p1, p2, p3))
  File "/home/xif033/miniconda3/envs/SGVtest/lib/python2.7/site-packages/bokeh/io/saving.py", line 86, in save
    _save_helper(obj, filename, resources, title, template)
  File "/home/xif033/miniconda3/envs/SGVtest/lib/python2.7/site-packages/bokeh/io/saving.py", line 150, in _save_helper
    with io.open(filename, mode="w", encoding="utf-8") as f:
IOError: [Errno 2] No such file or directory: '/home/xif033/Sandborn/SGVFiner/browser/665950.PRJNA40027.html'

Could you advise on what possibly caused this? Thank you very much for your help! Please let me know if more information is needed!

**Comment by talkorem** [comment]
Hello,

This is a bug that will be fixed in the next release. For now, just make sure that /home/xif033/Sandborn/SGVFiner/browser/ exists before running the code.

**Comment by xif033** [comment]
Thanks Tal! I was able to generate the dataframes after creating the folder. However, I also ran into the same question posted in https://github.com/segalab/SGVFinder/issues/12#issue-526314757. 

Could you help clarify the meaning of the numbers in the columns of the dataframes? Thank you very much! 

Best,
xIN
