### ISSUE TITLE
problem with SGVF_cmd.py

### ISSUE THREAD

**Issue by jjlea** [segalab/SGVFinder#17]
Dear developer,

I ran the command:
python SGVF_cmd.py  /data/SVG/test/*  /data/SVG/test/deletion.sgv /data/SVG/test/variable.sgv --csv_output --min_samp_cutoff 1

 /data/SVG/test/* include output files from SGVF_PerFile_cmd.py

But i got the error:
Traceback (most recent call last):
  File "SGVF_cmd.py", line 39, in <module>
    if args.byother:
AttributeError: 'Namespace' object has no attribute 'byother'

Thanks so much!

**Comment by treasure316** [comment]
Hello, I have the same problem. How can I solve it？ Thank you!
