### ISSUE TITLE
Unknown Extension options: 'include_path' and '-Wstrict-prototypes' not for C++

### ISSUE THREAD

**Issue by thejiahaozhang** [segalab/SGVFinder#2]
Hello. 
I have encountered some problems.
 What are the causes of these problems?

./anaconda2/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'include_path'
  warnings.warn(msg)
  
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]

./anaconda2/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
 
 
Best Wish!

**Comment by talkr** [comment]
This is typical output from cython. If you have .so files generated you're good to do.
