### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by rbrewster727** [segalab/SGVFinder#3]
I am attempting to run ICRA on a single paired-end sample using default parameters. Below is the command:

`python /labs/asbhatt/rbrewster/sgv_finder/SGVFinder/src/ICRA_cmd.py /labs/asbhatt/rbrewster/sgv_test/ A10 --pe --max_mismatch 8 --ignore_lengths --epsilon 1e-6 --max_iterations 100 --min_bins 10 --max_bins 100 --min_reads 100 --dense_region_coverage 60 --length_minimum 1e5 --length_maximum 2e7 --usage 'genomes' --use_theta`

This returns a `Segmentation fault` with no further information. Increasing the memory allocation to over 500 GB did not resolve the issue. Any assistance you can provide would be much appreciated.

**Comment by talkr** [comment]
Was a pmp file created?

**Comment by rbrewster727** [comment]
No. The only output is `Segmentation Fault` and no files are generated.

**Comment by talkr** [comment]
Do you have the file DataFiles/representatives.contigs.drepped.if_ujsn ?

**Comment by rbrewster727** [comment]
Yes, `representatives.contigs.drepped.if_ujsn` is in my DataFiles directory

**Comment by talkr** [comment]
OK, can you provide a list of the DataFiles directory please?

**Comment by rbrewster727** [comment]
Sure! Within my `DataFiles` directory are: 

- `2017-10-CAMI_genomes.filtered.dests`
- `2017-10-CAMI_genomes.filtered.gem`
- `2017-10-CAMI_genomes.filtered.idx` 
- `2017-10-CAMI_genomes.filtered.if_ujsn`
- `2017-10-CAMI_genomes.filtered.lens`
- `GEMSplit` (Directory): Contains `representatives.contigs.drepped_0.gem` and `representatives.contigs.drepped_1.gem`
- `orig_dsgv.df`
- `orig_frames` (Directory)
- `orig_vsgv.df`
- `representatives.contigs.drepped.dests`
- `representatives.contigs.drepped.dlen`
- `representatives.contigs.drepped.idx`
- `representatives.contigs.drepped.if_ujsn`
- `representatives.contigs.drepped.lens`
- `representatives.genes.drepped.annotations.df`
- `representatives.genomes.taxonomy.df`

**Comment by talkr** [comment]
Can you please try again with the latest code version?

**Comment by rbrewster727** [comment]
I downloaded the most recent code and now receive the following error when calling the original command:

`AssertionError: Could not find database file at /labs/asbhatt/rbrewster/sgv_finder/SGVFinder/src/../DataFiles/representatives.contigs.drepped.if_ujsn`

I confirmed that the `representatives.contigs.drepped.if_ujsn` is in the `DataFiles` directory.

**Comment by talkr** [comment]
Make sure that DataFiles itself is within
/labs/asbhatt/rbrewster/sgv_finder/SGVFinder/,
that is /labs/asbhatt/rbrewster/sgv_finder/SGVFinder/DataFiles
