### ISSUE TITLE
have trouble in installation

### ISSUE THREAD

**Issue by ucassee** [segalab/SGVFinder#6]
Dear developer,
       I don't know how to run `ICRA_cmd.py` .  I  use ` python /data2017/zhouyl/software/SGVFinder-master/src/ICRA_cmd.py  /data2017/zhouyl/test/svgtest/result /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1   --pe --use_theta` to run. But it went error with 

> Traceback (most recent call last):
  File "/data2017/zhouyl/software/SGVFinder-master/src/ICRA_cmd.py", line 44, in <module>
    args.outfol, args.max_mismatch, not args.consider_lengths, args.epsilon, args.max_iterations, \
AttributeError: 'Namespace' object has no attribute 'consider_lengths'

Hope to your reply. Thanks in advance.
Best regards

**Comment by talkr** [comment]
Can you please try again with the latest code version?

**Comment by ucassee** [comment]
Hi @talkr, 
      Thanks for your reply. When I update the software it still doesn't work with the following error:

> Traceback (most recent call last):
  File "/data2017/zhouyl/software/SGVFinder-master/src/ICRA_cmd.py", line 48, in <module>
    args.length_maximum, args.usage, args.use_theta)
  File "/data2017/zhouyl/software/SGVFinder-master/src/ICRA.py", line 30, in single_file
    gemmap_single_file(fq1, fq2, pmpf, indexl, seqdict, 0.05, 0.05, 2)
  File "/data2017/zhouyl/software/SGVFinder-master/src/GEMMapping.py", line 34, in gemmap_single_file
    threads=threads)
  File "/data2017/zhouyl/software/SGVFinder-master/src/GEMWrapperSlim.py", line 44, in dope_w_badread_removal
    suc, startnum = _dope(input1, input2, output_prefix, **kwargs) 
  File "/data2017/zhouyl/software/SGVFinder-master/src/GEMWrapperSlim.py", line 26, in _dope
    format(bin = GEM_BIN, **locals()), loglevel = logging.DEBUG)
  File "/data2017/zhouyl/software/SGVFinder-master/src/ICRAUtils.py", line 84, in _shell_command
    errnout = sbcheck_output(com, shell = True, stderr = subprocess.STDOUT)
  File "/data2017/share/tools/miniconda3/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'gem-mapper -I /data2017/zhouyl/software/SGVFinder-master/src/../DataFiles/GEMSplit/representatives.contigs.drepped_0.gem -1 /data2017/zhouyl/test/svgtest/result_1.fastq -2 /data2017/zhouyl/test/svgtest/result_2.fastq -o /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1/result_0 -q offset-33 --gem-quality-threshold 26 -m 0.05 -e 0.05 --min-matched-bases 0.8 --max-big-indel-length 15 -s 0 -d 20 -D 1 -p -E 0.3 --max-extendable-matches 20 --max-extensions-per-match 1 -v --max-insert-size 1000 -T 2' returned non-zero exit status 127

**Comment by talkr** [comment]
The error comes from the GEM mapper. Have you properly installed it? Can you run the command independently? What errors does it produce?

gem-mapper -I /data2017/zhouyl/software/SGVFinder-master/src/../DataFiles/GEMSplit/representatives.contigs.drepped_0.gem -1 /data2017/zhouyl/test/svgtest/result_1.fastq -2 /data2017/zhouyl/test/svgtest/result_2.fastq -o /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1/result_0 -q offset-33 --gem-quality-threshold 26 -m 0.05 -e 0.05 --min-matched-bases 0.8 --max-big-indel-length 15 -s 0 -d 20 -D 1 -p -E 0.3 --max-extendable-matches 20 --max-extensions-per-match 1 -v --max-insert-size 1000 -T 2

**Comment by ucassee** [comment]
Hi @talkr ,
       GEM mapper can call normally. But it run with the following error:

> Traceback (most recent call last):
  File "/data2017/zhouyl/software/SGVFinder-master/src/ICRA_cmd.py", line 48, in <module>
    args.length_maximum, args.usage, args.use_theta)
  File "/data2017/zhouyl/software/SGVFinder-master/src/ICRA.py", line 30, in single_file
    gemmap_single_file(fq1, fq2, pmpf, indexl, seqdict, 0.05, 0.05, 2)
  File "/data2017/zhouyl/software/SGVFinder-master/src/GEMMapping.py", line 34, in gemmap_single_file
    threads=threads)
  File "/data2017/zhouyl/software/SGVFinder-master/src/GEMWrapperSlim.py", line 44, in dope_w_badread_removal
    suc, startnum = _dope(input1, input2, output_prefix, **kwargs) 
  File "/data2017/zhouyl/software/SGVFinder-master/src/GEMWrapperSlim.py", line 26, in _dope
    format(bin = GEM_BIN, **locals()), loglevel = logging.DEBUG)
  File "/data2017/zhouyl/software/SGVFinder-master/src/ICRAUtils.py", line 84, in _shell_command
    errnout = sbcheck_output(com, shell = True, stderr = subprocess.STDOUT)
  File "/data2017/share/tools/miniconda3/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'gem-mapper -I /data2017/zhouyl/software/SGVFinder-master/src/../DataFiles/GEMSplit/representatives.contigs.drepped_0.gem -1 /data2017/zhouyl/test/svgtest/result_1.fastq -2 /data2017/zhouyl/test/svgtest/result_2.fastq -o /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1/result_0 -q offset-33 --gem-quality-threshold 26 -m 0.05 -e 0.05 --min-matched-bases 0.8 --max-big-indel-length 15 -s 0 -d 20 -D 1 -p -E 0.3 --max-extendable-matches 20 --max-extensions-per-match 1 -v --max-insert-size 1000 -T 2' returned non-zero exit status 1

**Comment by talkr** [comment]
The command is failing on calling the gem-mapper so it's obviously not running correctly. Can you please  run the following command from your command line and give me the output?:

`gem-mapper -I /data2017/zhouyl/software/SGVFinder-master/src/../DataFiles/GEMSplit/representatives.contigs.drepped_0.gem -1 /data2017/zhouyl/test/svgtest/result_1.fastq -2 /data2017/zhouyl/test/svgtest/result_2.fastq -o /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1/result_0 -q offset-33 --gem-quality-threshold 26 -m 0.05 -e 0.05 --min-matched-bases 0.8 --max-big-indel-length 15 -s 0 -d 20 -D 1 -p -E 0.3 --max-extendable-matches 20 --max-extensions-per-match 1 -v --max-insert-size 1000 -T 2`

**Comment by ucassee** [comment]
I guess  I don't use the right input file as there is no any output file.

> Welcome to GEM-mapper build 1.376 (beta) - (2013/04/06 02:13:06 GMT)
 (c) 2008-2013 Paolo Ribeca <paolo.ribeca@gmail.com>
 (c) 2010-2013 Santiago Marco Sola <santiagomsola@gmail.com>
 (c) 2010-2013 Leonor Frias Moya <leonor.frias@gmail.com>
For the terms of use, run the program with the option --show-license.
************************************************************************
* WARNING: this is a beta version, provided for testing purposes only; *
*          check for updates at <http://gemlibrary.sourceforge.net>.   *
************************************************************************
Fatal error (input.c:411,open_input_file)
 Could not stat file '/data2017/zhouyl/test/svgtest/result_1.fastq'

**Comment by talkr** [comment]
It seems that the file you gave as input:
`python /data2017/zhouyl/software/SGVFinder-master/src/ICRA_cmd.py /data2017/zhouyl/test/svgtest/result `

Is not accessible.
