### ISSUE TITLE
input file question

### ISSUE THREAD

**Issue by ucassee** [segalab/SGVFinder#7]
Dear developer，
       I want to use ICRA to calculate the bins coverage  in my metagenome. But I don't know how should I import my input file to ICRA. My pair-end fastq files are in `/dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1_*.fastq.  `  Where should I improt my metagenome-assembly file and bin genomes.  I try to test it with the following commond, it went error.

> python /data2017/zhouyl/software/SGVFinder-master/src/ICRA_cmd.py /data2017/zhouyl/test/svgtest/result /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1  --pe --use_theta

> gem-mapper -I /data2017/zhouyl/software/SGVFinder-master/src/../DataFiles/GEMSplit/representatives.contigs.drepped_0.gem -1 /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1_1.fastq -2 /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1_2.fastq -o /data2017/zhouyl/test/svgtest/result/TS01-LD10-1_0 -q offset-33 --gem-quality-threshold 26 -m 0.05 -e 0.05 --min-matched-bases 0.8 --max-big-indel-length 15 -s 0 -d 20 -D 1 -p -E 0.3 --max-extendable-matches 20 --max-extensions-per-match 1 -v --max-insert-size 1000 -T 2
Welcome to GEM-mapper build 1.376 (beta) - (2013/04/06 02:13:06 GMT)
 (c) 2008-2013 Paolo Ribeca <paolo.ribeca@gmail.com>
 (c) 2010-2013 Santiago Marco Sola <santiagomsola@gmail.com>
 (c) 2010-2013 Leonor Frias Moya <leonor.frias@gmail.com>
For the terms of use, run the program with the option --show-license.
************************************************************************
* WARNING: this is a beta version, provided for testing purposes only; *
*          check for updates at <http://gemlibrary.sourceforge.net>.   *
************************************************************************
Fri Jun 14 11:10:03 2019 -- Loading index (likely to take long)... done.
Fatal error (output.c:112,gem_output_file_new)
 Could not open file '/data2017/zhouyl/test/svgtest/result/TS01-LD10-1_0.map'

Hope to your reply. Thanks in advance.

**Comment by talkr** [comment]
This is not a problem with ICRA. You likely don't have write permissions for that directory (/data2017/zhouyl/test/svgtest/result)
