### ISSUE TITLE
how to use ICRA to calculate microbial abundances

### ISSUE THREAD

**Issue by ucassee** [segalab/SGVFinder#8]
Dear developer,
        I use this command  `python /data2017/zhouyl/software/SGVFinder-master/src/ICRA_cmd.py /data2017/zhouyl/test/svgtest/result /dataNew/User/zhouyl/sediment/TS01_LD10/CLEAN_READS/TS01-LD10-1 --pe --use_theta`   to run ICRA.  There are two output files `TS01-LD10-1.jsdel` and `TS01-LD10-1.pmp`. ICRA seems work now.   But where should I input my genomes to calculate microbial abundances of my metagenome.
Thanks in advance.

**Comment by davidzeevi** [comment]
Dear user,
We do not support microbial abundance calculations in ICRA. Should you want to pursue this, you may sum up the reads mapped to each genomic element in the .jsdel file and divide by the total sum.

**Comment by ucassee** [comment]
> We do not support microbial abundance calculations in ICRA. Should you want to pursue this, you may sum up the reads mapped to each genomic element in the .jsdel file and divide by the total sum.

Hi @davidzeevi, thanks for your reply.
I want to  calculate microbial abundance by ICRA. Can you introduce the file format to me. The following is the .jsdel file output by my data `[["M03609:19:000000000-AHFUY:1:1101:18854:2700",[["1298885.PRJNA190793",890101,890330,1,1]]]`
But I only import pair-end fastq files in  ICRA . How can I import genome from binning of my metagenome.
Thanks

**Comment by ucassee** [comment]
Hi @talkr 
       Running SGVF_PerFile_cmd.py needs three arguments ：
1、deltaf  （Is the .jsdel file from the ICRA?） 
2、outf       （I know it is the output file name）
3、average_read_length    （What should I input？）
       I don't know how to input these arguments. Can you give me some help? Thanks

**Comment by talkr** [comment]
1. yes.
3. The average read length in your original fastq file. Will usually be 75 or 100.
