### ISSUE TITLE
Disease Association Analysis

### ISSUE THREAD

**Issue by dombraccia** [segalab/SGVFinder#9]
Hello, I am interested in performing the Disease Association analysis as described in the manuscript. I have the Variable and Deletion SVs data frames (as `dsgv.df` and `vsgv.df`) from ICRA and SGVFinder output, but I am unable to locate the host risk factors data. I imagine there is a table somewhere with patient sample IDs in the rows and host factors in the columns, but I am unable to find it through accession PRJEB11532.. I'm also looking through the papers where the data originated: Personalized Nutrition by Prediction of Glycemic Responses (Zeevi et al. 2015) and "Detection of stable community structures within gut microbiota co-occurrence networks from different human populations" (Jackson et al. 2018) but I've been unable to find the data still.

Could you help me out with finding this information?

Thanks so much!
Domenick

**Comment by talkr** [comment]
Hi Domenick,
I suggest you contact the corresponding authors.
